#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

module_env = env_modules.Clone()

# Add ENet include path
module_env.Append(CPPPATH=["#thirdparty/enet/"])

module_env.add_source_files(env.modules_sources, "*.cpp")

# if env.debug_features:
module_env.add_source_files(env.modules_sources, "debug/*.cpp")

if env.editor_build:
    module_env.add_source_files(env.modules_sources, "editor/*.cpp")
